# Use root/example as user/password credentials
version: "3.1"

services:
  # node:
  # build:
  #   context: .
  #   dockerfile: Dockerfile
  #   # volumes:
  #   #   - .:/app
  #   # command: /usr/local/wait-for-it.sh mongosh:27017 -- npm run dev
  #   # env_file:
  #   #   - .env
  #   # ports:
  #   #   - "${PORT}:4000"
  #   networks:
  #     - node_network
  #   depends_on:
  #     - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./data/mongodb:/data/db"
    ports:
      - 27017:27017
    networks:
      - node_network

  digNikola: #dig mongo  # docker run -it --network chat-server_node_network nicolaka/netshoot
    image: nicolaka/netshoot
    networks:
      - node_network

networks:
  node_network:
