version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./data/mongodb:/data/db"
    ports:
      - 27017:27017
    networks:
      - node_network

networks:
  node_network:
# nicolaka/netshoot: Let us inspect another container in the same network and get pretty sensitive data from it (ip, etc)
# docker run -it --network chat-server_node_network nicolaka/netshoot
# dig mongo
